
name: Workflow that trigers from despatch event

on:
  workflow_dispatch:
    inputs:
      Go_Version:
        description: 'Set GO version'
        required: true
        default: '1.15'
        type: choice
        options:
        - '1.15'
        - '1.16'
        - '1.17'
      OS:
        description: 'Set Operating System'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
            - "windows-latest"
            - "ubuntu-latest"
            - "macos-latest"
jobs:
  log-the-inputs:
    runs-on: ${{ inputs.OS }}
    steps:
    - name: Checking out forked repository
      uses: actions/checkout@v3

    - name: Setup GO with ${{ inputs.Go_Version }} version
      uses: actions/setup-go@v3
      with:
       go-version: ${{ inputs.Go_Version }}
        
    - name: Build.
      run: GO111MODULE=auto go build -v ./...
    
    - name: Test
      run: GO111MODULE=auto go test -v ./... -json > TestResults-${{ inputs.Go_Version }}.json
      
    - name: Run main.go
      run: GO111MODULE=auto go run main.go

    - name: Upload Go test results
      uses: actions/upload-artifact@v3
      with:
        name: Go-results
        path: TestResults-${{ inputs.Go_Version }}.json
  
