name: Workflow that builds and pushes built docker image to DockerHub using matrix strategy

on:
  push:
    branches:
      - "master"
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  go_build_matrix:
    strategy:
      matrix:
        go_version: [1.18, 1.19]
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@f75d088332b07a08afadf6ac53c74509b9453f12
      with:
        registry: docker.io
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push docker image to DockerHub using action from GitHub MP.
      if: ${{ matrix.os  == 'ubuntu-22.04' }}
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/helloworld:${{ matrix.version }}_${{ env.GO_VERSION }}
        build-args: |
              "GOLANG_VERSION=${{ matrix.version }}"
              "OS=ubuntu:22.04"
      
    - name: Build and push docker image to DockerHub using action from GitHub MP.
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/helloworld:${{ matrix.version }}_${{ env.GO_VERSION }}
        build-args: |
              "GOLANG_VERSION=${{ matrix.version }}"
              "OS=ubuntu-20.04"