name: Workflow that builds and pushes built docker image to DockerHub.

on:
  push:
    branches:
      - "master"
env:
  GO_VERSION: "1.17"
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  # The value of STEP_TYPE should be 'using_cmd' or 'using_action'
  # If value is 'using_action' then use github actions from MP, otherwise use docker commands
  STEP_TYPE: 'using_cmd' 

jobs:
    build:
      runs-on: ubuntu-22.04
      steps:

        - name: Check out repository
          uses: actions/checkout@v3

        - name: Login to DockerHub
          uses: docker/login-action@f75d088332b07a08afadf6ac53c74509b9453f12
          with:
            registry: docker.io
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ env.DOCKERHUB_PASSWORD }}

        # Build image and push to DockerHub using docker commands.
        - name: Build docker image and push to DockerHub using docker commands.
          if: ${{ env.STEP_TYPE == 'using_cmd'}}
          run: |
           docker build --build-arg GOLANG_VERSION=$GO_VERSION -t $DOCKERHUB_USERNAME/helloworld:$GO_VERSION .
           docker push $DOCKERHUB_USERNAME/helloworld:$GO_VERSION
        
        # Another way to build and push docker image using actions from GitHub MP.
        - name: Setup Docker Buildx
          if: ${{ env.STEP_TYPE == 'using_action' }}
          uses: docker/setup-buildx-action@v2

        - name: Build and push docker image to DockerHub using action from DockerHub MP.
          if: ${{ env.STEP_TYPE == 'using_action' }}
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: ${{ env.DOCKERHUB_USERNAME }}/helloworld:${{ env.GO_VERSION }}
            build-args: "GOLANG_VERSION=${{ env.GO_VERSION }}"