name: Workflow that builds and pushes built docker image to DockerHub.

on:
  push:
    branches:
      - "master"
env:
  GO_VERSION: "1.16"
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

        - name: Check out repository
          uses: actions/checkout@v3

        - name: Login to DockerHub
          uses: docker/login-action@f75d088332b07a08afadf6ac53c74509b9453f12
          with:
            registry: docker.io
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build docker image
          run: |
            docker build --build-arg GOLANG_VERSION=$GO_VERSION -t $DOCKERHUB_USERNAME/helloworld:$GO_VERSION .

        - name: Push Docker image to DockerHub.
          run: docker push $DOCKERHUB_USERNAME/helloworld:$GO_VERSION