name: CI/CD build go application and create docker image

on:
  push:
    branches:
      - "master"

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Docker command
          run: docker ps
