name: CI/CD build go application and create docker image

on:
  push:
    branches:
      - "master"
env:
  GO_VERSION: "1.16"
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

        - name: Checking out repository
          uses: actions/checkout@v3

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build docker image and push it to DockerHub
          run: |
            sudo docker build --build-arg GOLANG_VERSION=$GO_VERSION -t $DOCKERHUB_USERNAME/helloworld_$GO_VERSION .
            sudo docker push $DOCKERHUB_USERNAME/helloworld_$GO_VERSION


 

